string(
  CONCAT
  CLANG_TIDY_CHECKS
  -checks=-*,
  cert-*,
  clang-diagnostic*,
  clang-analyzer-*,
  boost*,
  bugprone-*,
  clang-diagnostic-*,
  clang-analyzer-*,
  modernize-*,
  -modernize-use-trailing-return-type,
  -modernize-use-default-member-init,
  performance-*
)

set(
  CMAKE_CXX_CLANG_TIDY
  clang-tidy;
  -header-filter=${CMAKE_CURRENT_SOURCE_DIR};
  -warnings-as-errors=*;
  -checks=${CLANG_TIDY_CHECKS};
)
